[project]
name = "ml-this-time-fr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "curl-cffi>=0.16.2",
    "datetime>=6.0",
    "garminconnect>=0.3.11",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
]

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
